// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "keybol/internal/logic/mission"
	_ "keybol/internal/logic/user"
)
