// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Mission is the golang structure of table mission for DAO operations like Where/Data.
type Mission struct {
	g.Meta     `orm:"table:mission, do:true"`
	Id         interface{} //
	Name       interface{} //
	Detail     interface{} //
	Status     interface{} //
	CreateUid  interface{} //
	Deadline   *gtime.Time //
	Createtime *gtime.Time //
	Updatetime *gtime.Time //
}
