// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// MissionDao is the data access object for table mission.
type MissionDao struct {
	table   string         // table is the underlying table name of the DAO.
	group   string         // group is the database configuration group name of current DAO.
	columns MissionColumns // columns contains all the column names of Table for convenient usage.
}

// MissionColumns defines and stores column names for table mission.
type MissionColumns struct {
	Id         string //
	Name       string //
	Detail     string //
	Status     string //
	CreateUid  string //
	Deadline   string //
	Createtime string //
	Updatetime string //
}

// missionColumns holds the columns for table mission.
var missionColumns = MissionColumns{
	Id:         "id",
	Name:       "name",
	Detail:     "detail",
	Status:     "status",
	CreateUid:  "createUid",
	Deadline:   "deadline",
	Createtime: "createtime",
	Updatetime: "updatetime",
}

// NewMissionDao creates and returns a new DAO object for table data access.
func NewMissionDao() *MissionDao {
	return &MissionDao{
		group:   "default",
		table:   "mission",
		columns: missionColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *MissionDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *MissionDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *MissionDao) Columns() MissionColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *MissionDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *MissionDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *MissionDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
