// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"keydol/internal/service/internal/dao/internal"
)

// missionDao is the data access object for table mission.
// You can define custom methods on it to extend its functionality as you wish.
type missionDao struct {
	*internal.MissionDao
}

var (
	// Mission is globally public accessible object for table mission operations.
	Mission = missionDao{
		internal.NewMissionDao(),
	}
)

// Fill with you ideas below.
