// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"keybol/internal/model"
)

type (
	IMission interface {
		Create(ctx context.Context, in model.MissionCreateInput) (out model.MissionCreateOutput, err error)
		Delete(ctx context.Context, in model.MissionDeleteInput) (out model.MissionDeleteOutput, err error)
		Update(ctx context.Context, in model.MissionUpdateInput) (out model.MissionUpdateOutput, err error)
		GetListOfUser(ctx context.Context, in model.MissionQueryByUserIdInput) (out *model.MissionQueryByUserIdOutput, err error)
	}
)

var (
	localMission IMission
)

func Mission() IMission {
	if localMission == nil {
		panic("implement not found for interface IMission, forgot register?")
	}
	return localMission
}

func RegisterMission(i IMission) {
	localMission = i
}
