// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"keybol/internal/model"
)

type (
	IUser interface {
		Register(ctx context.Context, in model.UserRegisterInput) (out model.UserRegisterOutput, err error)
		GetUserInfo(ctx context.Context, in model.UserGetInfoInput) (out model.UserGetInfoOutput, err error)
		List(ctx context.Context, in model.UserListInput) (out *model.UserListOutput, err error)
	}
)

var (
	localUser IUser
)

func User() IUser {
	if localUser == nil {
		panic("implement not found for interface IUser, forgot register?")
	}
	return localUser
}

func RegisterUser(i IUser) {
	localUser = i
}
