// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-12-04 17:53:57
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Mission is the golang structure of table mission for DAO operations like Where/Data.
type Mission struct {
	g.Meta `orm:"table:mission, do:true"`
	Id     interface{} //
	Name   interface{} //
	Detail interface{} //
}
