// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-12-04 17:53:57
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// User is the golang structure of table user for DAO operations like Where/Data.
type User struct {
	g.Meta   `orm:"table:user, do:true"`
	Id       interface{} //
	Username interface{} //
	Password interface{} //
}
