// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-12-04 17:53:57
// =================================================================================

package entity

// Mission is the golang structure for table mission.
type Mission struct {
	Id     string `json:"id"     ` //
	Name   string `json:"name"   ` //
	Detail string `json:"detail" ` //
}
