// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id         int         `json:"id"         ` //
	Username   string      `json:"username"   ` //
	Password   string      `json:"password"   ` //
	Email      string      `json:"email"      ` //
	Phone      string      `json:"phone"      ` //
	Createtime *gtime.Time `json:"createtime" ` //
	Updatetime *gtime.Time `json:"updatetime" ` //
}
