// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-12-04 17:53:57
// =================================================================================

package entity

// User is the golang structure for table user.
type User struct {
	Id       string `json:"id"       ` //
	Username string `json:"username" ` //
	Password string `json:"password" ` //
}
